## NumPy :-
* NumPy is the short form of Numerical Python.
* In 2005, Travis Oliphant created NumPy package.
* NumPy is a package that defines a multi-dimensional array object and associates fast math functions that operate on inbuilt.
* Functions for working in domain of linar Algebra, Fourier Transformation and Matrices.
* It is the fundamental package of scientific computing in Python.
#### Advantages :-
1. NumPy uses much less memory to store data.
2. NumPy makes it extremely easy to perform mathematical operations on it.
3. Used for the creation of n-dimensional arrays.
4. Finding elements in NumPy array is easy.
#### Disadvantage :-
1. It uses much less memory to store data.
2. NumPy makes it extremely easy to perform mathematical operations on it.
3. Used for the creation of n-dimensional arrays.
4. Finding elements in NumPy array is easy.

### Arrays :-
1. An array is defined as a collection of items that are stored at contiguous memory locations.
2. It is a container which can hold a fixed number of items , and these items should be of the same type.
3. A combination of arrays saves a lot of time. The array can reduce the overall size of the code.
#### Advantages :-
1. A list can't directly handle Mathematical Operations, while Array can.
2. An Array consumes less memory than a List.
3. Using an Array is faste than list.
4. A List can store different datatypes, while you can't do that in an Array.

In [7]:
import numpy as np
a = np.array([20, 30, 40])
b = np.array([50, 60, 70])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[20 30 40]
[50 60 70]
[ 70  90 110]
[-30 -30 -30]
[1000 1800 2800]
[0.4        0.5        0.57142857]


In [8]:
a = np.array([40, 50, 58.56])
print(a)

[40.   50.   58.56]


#### Arrays v/s Lists :-
* A List can't directly handle Mathematical Operations, while Array can.
* An Array consumes less memory than a List.
* Using an Array is faster than list.
* A List can store different datatypes, while you can't do that in an Array.
* A List is easier to modify since a list store each element individually, it is easier to add and delete an element than an array does.
* In Lists one can have nested data with different size, while you can't do the same in array.

### Numpy :- Creating Arrays, Slicing and Attributes

In [1]:
import numpy as np

In [7]:
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[30, 50, 90, 50]])
print(arr)
print(type(arr))

[[10 20 30 40]
 [50 60 70 80]
 [30 50 90 50]]
<class 'numpy.ndarray'>


In [11]:
arr = np.array([10, 20, 30, 40])
print(arr[0:3])
print(arr[0:])
print(arr[3:])

[10 20 30]
[10 20 30 40]
[40]


In [13]:
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(arr[0:2, 1:2])

[[20]
 [60]]


#### Attribute :-
1. shape
2. size
3. ndim - N Dimensional
4. dtype - Data Type

In [18]:
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[30, 50, 90, 50]])
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 4)
12
2
int32


#### Inspecting an Array :-
* Functions :-
   1. a.shape - Array Dimensions
   2. len(a) - Length of Array
   3. b.ndim - Number of array dimensions
   4. e.size - Number of array elements
   5. b.dype - Data type of array elements
   6. b.astype(int) - Convert on array to a different type

In [21]:
import numpy as np
a = [[30, 50], [60, 80]]
arr = np.array(a)
print(arr)

[[30 50]
 [60 80]]


In [22]:
print(arr.shape) #rows, columns

(2, 2)


In [23]:
print(len(arr)) # number of nested values

2


In [24]:
print(np.size(arr)) # number of elements

4


In [25]:
print(type(arr)) # types of variable

<class 'numpy.ndarray'>


In [28]:
print(arr.dtype) # datatype of array

int32


Conversion of datatype

In [29]:
print(arr.astype(float))

[[30. 50.]
 [60. 80.]]


In [30]:
print(arr.astype(str))

[['30' '50']
 ['60' '80']]


In [31]:
print(arr.astype(int))

[[30 50]
 [60 80]]


#### Mathematical Operations and Functions on Array
* Functions :-
  1. g = a-b
  2. np.subtract(a, b)
  3. b + a n
  4. p.add(b, a)
  5. a / b
  6. np.divide(a, b)
  7. a * b
  8. np.multiply(a, b)
  9. np.exp(b)
  10. np.sqrt(b)
  11. np.pow(a)

In [32]:
import numpy as np

In [33]:
arr1 = np.array([30, 40, 50, 60, 80])
arr2 = np.array([50, 60, 80, 90, 20])

In [35]:
print(arr1+arr2)

[ 80 100 130 150 100]


In [36]:
print(np.add(arr1, arr2))

[ 80 100 130 150 100]


In [37]:
print(arr1-arr2)

[-20 -20 -30 -30  60]


In [38]:
print(np.subtract(arr1, arr2))

[-20 -20 -30 -30  60]


In [39]:
print(arr1*arr2)

[1500 2400 4000 5400 1600]


In [40]:
print(np.multiply(arr1, arr2))

[1500 2400 4000 5400 1600]


In [41]:
print(arr1/arr2)

[0.6        0.66666667 0.625      0.66666667 4.        ]


In [42]:
print(np.divide(arr1, arr2))

[0.6        0.66666667 0.625      0.66666667 4.        ]


In [45]:
arr1 = np.array([3, 4, 5, 6, 8])
arr2 = np.array([3])
print(np.power(arr1, arr2))

[ 27  64 125 216 512]


In [46]:
arr1 = np.array([3, 4, 5, 6, 8])
print(np.sqrt(arr1))

[1.73205081 2.         2.23606798 2.44948974 2.82842712]


#### Combining and Splitting Array :-

Join and Split

In [47]:
a = [3, 40, 50]
b = [5, 5, 3]
print(a+b)

[3, 40, 50, 5, 5, 3]


In [50]:
# Concatenate

arr1 = np.array([[30, 40], [50, 60]])
arr2 = np.array([[5, 5], [3, 6]])
print(np.concatenate([arr1, arr2]))

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  6]]


In [52]:
print(np.concatenate([arr1, arr2], axis = 0))

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  6]]


In [53]:
print(np.concatenate([arr1, arr2], axis = 1))

[[30 40  5  5]
 [50 60  3  6]]


In [56]:
print(np.hstack([arr1, arr2])) # Horizontal concatenation

[[30 40  5  5]
 [50 60  3  6]]


In [57]:
print(np.vstack([arr1, arr2])) # Vertical concatenation

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  6]]


In [58]:
a = np.array([20, 40, 30, 40, 10, 20])
print(np.array_split(a, 3))

[array([20, 40]), array([30, 40]), array([10, 20])]


In [59]:
a = np.array([20, 40, 30, 40, 10, 20])
print(np.array_split(a, 5))
print(a)

[array([20, 40]), array([30]), array([40]), array([10]), array([20])]
[20 40 30 40 10 20]


In [60]:
a = np.array([20, 40, 30, 40, 10, 20])
b = (np.array_split(a, 5))
print(b)

[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


#### Adding and Removing Elements in the Arrays :-
Functions :-
* np.append(h,g) - Append items to an array
* np.insert(a, 1, 5) - Inserts items in an array
* np.delete(a,[1)]) - Delete items from an array

In [65]:
import numpy as np

In [70]:
a = np.array([[20, 40], [60, 80]])
print(np.append(a, [90, 100]))

[ 20  40  60  80  90 100]


In [71]:
print(np.insert(a, 1, 50)) # array, index, value

[20 50 40 60 80]


In [72]:
print(np.insert(a, 1, [50, 60], axis = 1))

[[20 50 40]
 [60 60 80]]


In [74]:
print(a)
print(np.delete(a, 1))

[[20 40]
 [60 80]]
[20 60 80]


#### Numpy - Sort, Filter, and Search

In [75]:
arr = np.array([2,3,4,5,6,8,6])
print(np.sort(arr))

[2 3 4 5 6 6 8]


In [77]:
arr = np.array([[2,3,4,5,6,8,6],[2,8,36,99,0,56,2]])
print(np.sort(arr))

[[ 2  3  4  5  6  6  8]
 [ 0  2  2  8 36 56 99]]


In [78]:
arr = np.array([3,4,1,7,8])
s = np.where(arr == 4)
print(s)

(array([1], dtype=int64),)


In [81]:
arr = np.array([1,2,3,4,6,7,9])
s = np.searchsorted(arr, 2)
print(s)

1


In [83]:
arr = np.array([20,30,40,50])
fa = [True, False, True, False]
new = arr[fa]
print(new)

[20 40]


In [84]:
arr = np.array([20,30,40,50])
fa = arr > 35
new = arr[fa]
print(new)

[40 50]


In [85]:
arr = np.array([20,30,40,50])
fa = arr % 3 == 0
new = arr[fa]
print(new)

[30]


#### Aggregating Functions in Numpy

In [87]:
import numpy as np

In [88]:
a = np.array([20,40,60,70])
print(np.sum(a))

190


In [89]:
print(np.min(a))

20


In [90]:
print(np.max(a))

70


In [95]:
print(np.size(a))

4


In [96]:
print(np.mean(a))

47.5


In [98]:
print(np.median(a))

50.0


In [99]:
print(np.cumsum(a))

[ 20  60 120 190]


In [100]:
print(np.cumprod(a))

[     20     800   48000 3360000]


In [103]:
a = [100, 150, 199, 200, 250, 130]
b = [10, 30, 50, 100, 30, 40]

price = np.array(a)
quantity = np.array(b)
print(price, "\n", quantity)

[100 150 199 200 250 130] 
 [ 10  30  50 100  30  40]


In [104]:
print(np.sum(price))

1029


In [105]:
print(np.cumsum([price, quantity]))

[ 100  250  449  649  899 1029 1039 1069 1119 1219 1249 1289]


In [107]:
c = (np.cumprod([price, quantity], axis = 0))
print(c)

[[  100   150   199   200   250   130]
 [ 1000  4500  9950 20000  7500  5200]]


In [108]:
print(c[1].sum())

48150


#### Statictical Functions in Arrays :-

In [113]:
import numpy as np
import statistics as stats
baked_food = [200, 300, 150, 130, 200, 280, 170, 188]
a = np.array(baked_food)
print(np.mean(baked_food)) # sum of all the values / numbers of values

202.25


In [114]:
print(np.median(a))

194.0


In [116]:
print(stats.mode(a))

200


In [117]:
print(np.std(baked_food))

55.68157235567257


In [118]:
print(np.var(baked_food))

3100.4375


corrcoef
* -1 represent inversely proportional relationship
* 1 represents proportional relationship
* 0 means no relationship

In [120]:
tobacco_consumption = [30, 50, 10, 30, 50, 40]
deaths = [100, 120, 70, 100, 120, 112]
print(np.corrcoef([tobacco_consumption, deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [121]:
price = [300,100, 350, 150, 200]
sales = [10, 20, 7, 17, 3]

In [122]:
print(np.corrcoef([price, sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
